-- RETAIL OPERATION ANALYSIS

-- WE ARE GOING TO EXPLORE THE DATA, CREATING INSIGHTFUL BUSINESS QUERIES TO ASSESS THE RETAIL OPERATIONS

-- SECTION 1--SALES ANALYSIS PERFOMANCE

-- revenue generated by each product
SELECT product_name,
sum(quantity * (unit_price * (1- discount)) ) as total_revenue
FROM retail_products AS rp
JOIN  retail_order_items AS ro
	ON rp.product_id=ro.product_id
GROUP BY product_name
order by total_revenue desc;


-- which category is our main revenue engine
SELECT  category,
ROUND(sum(quantity * (unit_price * (1- discount))),2) as total_revenue
FROM retail_products AS rp
JOIN  retail_order_items AS ro
	ON rp.product_id=ro.product_id
GROUP BY  category
order by total_revenue desc;


-- CUSTOMER AND GEOGRAPHIC INSIGHT
-- How does revenue compare across Home Office, Retail, and Corporate segments?
SELECT segment,
 ROUND(sum(quantity * (unit_price * (1- discount))), 0)as total_revenue
FROM retail_order_items roi
JOIN retail_orders ro
	ON roi. order_id = ro.order_id
JOIN retail_customers rc
	ON ro.customer_id = rc. customer_id
GROUP BY segment;

-- we want to identify the number of customers in each city and which city does the majority of our customers reside
SELECT city, COUNT(*) as no_customers
FROM retail_customers
GROUP BY city
ORDER BY no_customers desc;

-- average discount per category...and from the insight allcategories hover around 15%
SELECT category,
ROUND( AVG(discount * 100),2) AS avg_discount_pct
FROM retail_order_items O
JOIN retail_products P
	ON O.product_id = p.product_id
GROUP BY category;

-- here we want to account on the amount of orders placed in each month of the year
SELECT 
    MONTHNAME(order_date) AS month_name,
    COUNT(order_id) AS monthly_order_volume
FROM retail_orders
GROUP BY MONTH(order_date), MONTHNAME(order_date)
ORDER BY MONTH(order_date);

-- orders with pending payments
SELECT O.order_id, payment_status
FROM retail_orders O
JOIN retail_payments P
	ON O. order_id = P.order_id
WHERE payment_status = 'pending'
GROUP BY  O.order_id, payment_status;


-- we want to account on which mode of payment is most preffered by our customers
SELECT payment_method, COUNT(order_id) as usage_count
FROM retail_payments
GROUP BY payment_method
ORDER BY usage_count desc;
-- from our finding, bank transfer is most preffered while mpesa is the least used

-- this is the value of revunue lost through discount
SELECT ROUND(SUM(quantity * unit_price * discount), 2) as total_discount_value 
FROM retail_order_items;

-- customer life value (CLV) for the top 5 customers
SELECT c.customer_id,
ROUND(sum(quantity * (unit_price * (1- discount))), 1) as custome_lifetime_value
FROM retail_customers c
JOIN retail_orders o
	ON c.customer_id = o.customer_id
JOIN retail_order_items ro
	ON o.order_id = ro.order_id
GROUP BY customer_id
ORDER BY custome_lifetime_value DESC
LIMIT 5;


-- we want to account for the orders which bring high revenue to the business
SELECT order_id,
ROUND(sum(quantity * (unit_price * (1- discount))), 2) AS high_order_value
FROM retail_order_items
GROUP BY order_id
HAVING high_order_value > 15000
ORDER BY high_order_value DESC;
-- we can clearly see that ORD00673 and ORD00968 take top spots for the amount of revenue 


-- AGE DEMOGRAPHICS VS REVENUE
-- from the demographic dataset we devide the age group to three categories and as the results show, middle aged people are generate higher revenue compared to the other age groups
SELECT
CASE
	WHEN age <30 THEN 'under 30'
    WHEN age between 30 and 50 THEN '30-50'
    WHEN age >50 THEN 'over 50'
END age_group,
ROUND(sum(quantity * (unit_price * (1- discount))), 2) as total_revenue
FROM retail_customers c
JOIN retail_orders o
	ON c.customer_id = o.customer_id
JOIN retail_order_items ro
	ON o.order_id = ro.order_id
GROUP BY 1
ORDER BY total_revenue desc;


-- here we calculated the payment success rate of each payment method
SELECT payment_method, 
       ROUND(SUM(CASE WHEN payment_status = 'Paid' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as success_rate
FROM retail_payments GROUP BY payment_method;


-- by using the window function we were able to calculate the running total of revenue
SELECT order_date, 
       ROUND(SUM(SUM(quantity * unit_price * (1 - discount))) OVER(ORDER BY order_date), 2) as running_total
FROM retail_orders o JOIN retail_order_items oi ON o.order_id = oi.order_id
GROUP BY order_date;


-- the pareto analysis
WITH ProdRev AS (
    SELECT product_id, 
    SUM(quantity * unit_price * (1-discount)) as rev
    FROM retail_order_items GROUP BY 1
)
SELECT product_id, ROUND(rev, 2) as rev, 
       ROUND(SUM(rev) OVER(ORDER BY rev DESC) * 
       100.0 / SUM(rev) OVER(), 2) as cumulative_pct
FROM ProdRev;



-- top customer per city
WITH CitySpend AS (
    SELECT c.city, c.customer_id, SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) as total_spent
    FROM retail_customers c
    JOIN retail_orders o ON c.customer_id = o.customer_id
    JOIN retail_order_items oi ON o.order_id = oi.order_id
    GROUP BY 1, 2
)
SELECT * FROM (
    SELECT *, DENSE_RANK() OVER(PARTITION BY city ORDER BY total_spent DESC) as rank
    FROM CitySpend
) WHERE rank = 1;